get:
  tags:
    - campaigns
    - dbs
    - fbs
    - express
    - fby
  x-auth-scopes:
    - all-methods
    - settings
    - finance-and-accounting
    - offers-and-cards
    - offers-and-cards:read-only
    - pricing
    - pricing:read-only
    - inventory-and-orders
    - inventory-and-orders:read-only
    - promotion
    - promotion:read-only
    - communication
  operationId: getCampaignSettings
  summary: Настройки магазина
  description: >
    Возвращает информацию о настройках магазина, идентификатор которого указан в
    запросе.

    |**⚙️ Лимит:** 1000 запросов в час|

    |-|
  parameters:
    - $ref: ../components/parameters/CampaignId.yaml
  responses:
    '200':
      description: Настройки магазина.
      content:
        application/json:
          schema:
            $ref: ../components/schemas/GetCampaignSettingsResponse.yaml
    '400':
      $ref: ../components/responses/400.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '420':
      $ref: ../components/responses/420.yaml
    '500':
      $ref: ../components/responses/500.yaml
