description: Параметр со списком устанавливаемых значений.
type: object
required:
  - parameterId
  - values
properties:
  parameterId:
    description: Идентификатор параметра, для которого выставляется значение.
    type: integer
    format: int64
  values:
    description: Список значений, устанавливаемых для параметра.
    type: array
    items:
      $ref: ./ParameterValueDTO.yaml
